language: php

php:
  - '7.0.22'
  - '7.1'
  - '7.2'

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls
